INFO 10-23 21:54:15 [__init__.py:216] Automatically detected platform cuda.
[1;36m(APIServer pid=298084)[0;0m INFO 10-23 21:54:17 [api_server.py:1839] vLLM API server version 0.11.0
[1;36m(APIServer pid=298084)[0;0m INFO 10-23 21:54:17 [utils.py:233] non-default args: {'host': '0.0.0.0', 'port': 8888, 'model': '/NAS/caizj/models/deepseek/DeepSeek-R1-Distill-Qwen-1.5B/'}
[1;36m(APIServer pid=298084)[0;0m INFO 10-23 21:54:17 [model.py:547] Resolved architecture: Qwen2ForCausalLM
[1;36m(APIServer pid=298084)[0;0m `torch_dtype` is deprecated! Use `dtype` instead!
[1;36m(APIServer pid=298084)[0;0m INFO 10-23 21:54:17 [model.py:1510] Using max model len 131072
[1;36m(APIServer pid=298084)[0;0m INFO 10-23 21:54:17 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 10-23 21:54:21 [__init__.py:216] Automatically detected platform cuda.
[1;36m(EngineCore_DP0 pid=298381)[0;0m INFO 10-23 21:54:23 [core.py:644] Waiting for init message from front-end.
[1;36m(EngineCore_DP0 pid=298381)[0;0m INFO 10-23 21:54:23 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='/NAS/caizj/models/deepseek/DeepSeek-R1-Distill-Qwen-1.5B/', speculative_config=None, tokenizer='/NAS/caizj/models/deepseek/DeepSeek-R1-Distill-Qwen-1.5B/', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/NAS/caizj/models/deepseek/DeepSeek-R1-Distill-Qwen-1.5B/, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[1;36m(EngineCore_DP0 pid=298381)[0;0m INFO 10-23 21:54:25 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708] EngineCore failed to start.
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708] Traceback (most recent call last):
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/core.py", line 699, in run_engine_core
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/core.py", line 498, in __init__
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]                      executor_fail_callback)
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]                      ^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/core.py", line 83, in __init__
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]                           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     self._init_executor()
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     ~~~~~~~~~~~~~~~~~~~^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/executor/uniproc_executor.py", line 54, in _init_executor
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     self.collective_rpc("init_device")
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     return [run_method(self.driver_worker, method, args, kwargs)]
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/utils/__init__.py", line 3122, in run_method
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     return func(*args, **kwargs)
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/worker/worker_base.py", line 259, in init_device
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     ~~~~~~~~~~~~~~~~~~~~~~~^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/worker/gpu_worker.py", line 187, in init_device
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     raise ValueError(
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     ...<7 lines>...
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708]     )
[1;36m(EngineCore_DP0 pid=298381)[0;0m ERROR 10-23 21:54:26 [core.py:708] ValueError: Free memory on device (20.73/23.69 GiB) on startup is less than desired GPU memory utilization (0.9, 21.32 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
[1;36m(EngineCore_DP0 pid=298381)[0;0m Process EngineCore_DP0:
[1;36m(EngineCore_DP0 pid=298381)[0;0m Traceback (most recent call last):
[1;36m(EngineCore_DP0 pid=298381)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
[1;36m(EngineCore_DP0 pid=298381)[0;0m     self.run()
[1;36m(EngineCore_DP0 pid=298381)[0;0m     ~~~~~~~~^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/multiprocessing/process.py", line 108, in run
[1;36m(EngineCore_DP0 pid=298381)[0;0m     self._target(*self._args, **self._kwargs)
[1;36m(EngineCore_DP0 pid=298381)[0;0m     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/core.py", line 712, in run_engine_core
[1;36m(EngineCore_DP0 pid=298381)[0;0m     raise e
[1;36m(EngineCore_DP0 pid=298381)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/core.py", line 699, in run_engine_core
[1;36m(EngineCore_DP0 pid=298381)[0;0m     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_DP0 pid=298381)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/core.py", line 498, in __init__
[1;36m(EngineCore_DP0 pid=298381)[0;0m     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_DP0 pid=298381)[0;0m     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m                      executor_fail_callback)
[1;36m(EngineCore_DP0 pid=298381)[0;0m                      ^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/core.py", line 83, in __init__
[1;36m(EngineCore_DP0 pid=298381)[0;0m     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_DP0 pid=298381)[0;0m                           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_DP0 pid=298381)[0;0m     self._init_executor()
[1;36m(EngineCore_DP0 pid=298381)[0;0m     ~~~~~~~~~~~~~~~~~~~^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/executor/uniproc_executor.py", line 54, in _init_executor
[1;36m(EngineCore_DP0 pid=298381)[0;0m     self.collective_rpc("init_device")
[1;36m(EngineCore_DP0 pid=298381)[0;0m     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
[1;36m(EngineCore_DP0 pid=298381)[0;0m     return [run_method(self.driver_worker, method, args, kwargs)]
[1;36m(EngineCore_DP0 pid=298381)[0;0m             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/utils/__init__.py", line 3122, in run_method
[1;36m(EngineCore_DP0 pid=298381)[0;0m     return func(*args, **kwargs)
[1;36m(EngineCore_DP0 pid=298381)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/worker/worker_base.py", line 259, in init_device
[1;36m(EngineCore_DP0 pid=298381)[0;0m     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_DP0 pid=298381)[0;0m     ~~~~~~~~~~~~~~~~~~~~~~~^^
[1;36m(EngineCore_DP0 pid=298381)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/worker/gpu_worker.py", line 187, in init_device
[1;36m(EngineCore_DP0 pid=298381)[0;0m     raise ValueError(
[1;36m(EngineCore_DP0 pid=298381)[0;0m     ...<7 lines>...
[1;36m(EngineCore_DP0 pid=298381)[0;0m     )
[1;36m(EngineCore_DP0 pid=298381)[0;0m ValueError: Free memory on device (20.73/23.69 GiB) on startup is less than desired GPU memory utilization (0.9, 21.32 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
[rank0]:[W1023 21:54:26.834164981 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[1;36m(APIServer pid=298084)[0;0m Traceback (most recent call last):
[1;36m(APIServer pid=298084)[0;0m   File "<frozen runpy>", line 198, in _run_module_as_main
[1;36m(APIServer pid=298084)[0;0m   File "<frozen runpy>", line 88, in _run_code
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/entrypoints/openai/api_server.py", line 1953, in <module>
[1;36m(APIServer pid=298084)[0;0m     uvloop.run(run_server(args))
[1;36m(APIServer pid=298084)[0;0m     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/uvloop/__init__.py", line 96, in run
[1;36m(APIServer pid=298084)[0;0m     return __asyncio.run(
[1;36m(APIServer pid=298084)[0;0m            ~~~~~~~~~~~~~^
[1;36m(APIServer pid=298084)[0;0m         wrapper(),
[1;36m(APIServer pid=298084)[0;0m         ^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m     ...<2 lines>...
[1;36m(APIServer pid=298084)[0;0m         **run_kwargs
[1;36m(APIServer pid=298084)[0;0m         ^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m     )
[1;36m(APIServer pid=298084)[0;0m     ^
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/asyncio/runners.py", line 195, in run
[1;36m(APIServer pid=298084)[0;0m     return runner.run(main)
[1;36m(APIServer pid=298084)[0;0m            ~~~~~~~~~~^^^^^^
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/asyncio/runners.py", line 118, in run
[1;36m(APIServer pid=298084)[0;0m     return self._loop.run_until_complete(task)
[1;36m(APIServer pid=298084)[0;0m            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
[1;36m(APIServer pid=298084)[0;0m   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/uvloop/__init__.py", line 48, in wrapper
[1;36m(APIServer pid=298084)[0;0m     return await main
[1;36m(APIServer pid=298084)[0;0m            ^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/entrypoints/openai/api_server.py", line 1884, in run_server
[1;36m(APIServer pid=298084)[0;0m     await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/entrypoints/openai/api_server.py", line 1902, in run_server_worker
[1;36m(APIServer pid=298084)[0;0m     async with build_async_engine_client(
[1;36m(APIServer pid=298084)[0;0m                ~~~~~~~~~~~~~~~~~~~~~~~~~^
[1;36m(APIServer pid=298084)[0;0m             args,
[1;36m(APIServer pid=298084)[0;0m             ^^^^^
[1;36m(APIServer pid=298084)[0;0m             client_config=client_config,
[1;36m(APIServer pid=298084)[0;0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m     ) as engine_client:
[1;36m(APIServer pid=298084)[0;0m     ^
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/contextlib.py", line 214, in __aenter__
[1;36m(APIServer pid=298084)[0;0m     return await anext(self.gen)
[1;36m(APIServer pid=298084)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/entrypoints/openai/api_server.py", line 180, in build_async_engine_client
[1;36m(APIServer pid=298084)[0;0m     async with build_async_engine_client_from_engine_args(
[1;36m(APIServer pid=298084)[0;0m                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
[1;36m(APIServer pid=298084)[0;0m             engine_args,
[1;36m(APIServer pid=298084)[0;0m             ^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m     ...<2 lines>...
[1;36m(APIServer pid=298084)[0;0m             client_config=client_config,
[1;36m(APIServer pid=298084)[0;0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m     ) as engine:
[1;36m(APIServer pid=298084)[0;0m     ^
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/contextlib.py", line 214, in __aenter__
[1;36m(APIServer pid=298084)[0;0m     return await anext(self.gen)
[1;36m(APIServer pid=298084)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/entrypoints/openai/api_server.py", line 225, in build_async_engine_client_from_engine_args
[1;36m(APIServer pid=298084)[0;0m     async_llm = AsyncLLM.from_vllm_config(
[1;36m(APIServer pid=298084)[0;0m         vllm_config=vllm_config,
[1;36m(APIServer pid=298084)[0;0m     ...<4 lines>...
[1;36m(APIServer pid=298084)[0;0m         client_count=client_count,
[1;36m(APIServer pid=298084)[0;0m         client_index=client_index)
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/utils/__init__.py", line 1572, in inner
[1;36m(APIServer pid=298084)[0;0m     return fn(*args, **kwargs)
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/async_llm.py", line 207, in from_vllm_config
[1;36m(APIServer pid=298084)[0;0m     return cls(
[1;36m(APIServer pid=298084)[0;0m         vllm_config=vllm_config,
[1;36m(APIServer pid=298084)[0;0m     ...<8 lines>...
[1;36m(APIServer pid=298084)[0;0m         client_index=client_index,
[1;36m(APIServer pid=298084)[0;0m     )
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/async_llm.py", line 134, in __init__
[1;36m(APIServer pid=298084)[0;0m     self.engine_core = EngineCoreClient.make_async_mp_client(
[1;36m(APIServer pid=298084)[0;0m                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
[1;36m(APIServer pid=298084)[0;0m         vllm_config=vllm_config,
[1;36m(APIServer pid=298084)[0;0m         ^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m     ...<4 lines>...
[1;36m(APIServer pid=298084)[0;0m         client_index=client_index,
[1;36m(APIServer pid=298084)[0;0m         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m     )
[1;36m(APIServer pid=298084)[0;0m     ^
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/core_client.py", line 102, in make_async_mp_client
[1;36m(APIServer pid=298084)[0;0m     return AsyncMPClient(*client_args)
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/core_client.py", line 769, in __init__
[1;36m(APIServer pid=298084)[0;0m     super().__init__(
[1;36m(APIServer pid=298084)[0;0m     ~~~~~~~~~~~~~~~~^
[1;36m(APIServer pid=298084)[0;0m         asyncio_mode=True,
[1;36m(APIServer pid=298084)[0;0m         ^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m     ...<3 lines>...
[1;36m(APIServer pid=298084)[0;0m         client_addresses=client_addresses,
[1;36m(APIServer pid=298084)[0;0m         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m     )
[1;36m(APIServer pid=298084)[0;0m     ^
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/core_client.py", line 448, in __init__
[1;36m(APIServer pid=298084)[0;0m     with launch_core_engines(vllm_config, executor_class,
[1;36m(APIServer pid=298084)[0;0m          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m                              log_stats) as (engine_manager,
[1;36m(APIServer pid=298084)[0;0m                              ^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/contextlib.py", line 148, in __exit__
[1;36m(APIServer pid=298084)[0;0m     next(self.gen)
[1;36m(APIServer pid=298084)[0;0m     ~~~~^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/utils.py", line 732, in launch_core_engines
[1;36m(APIServer pid=298084)[0;0m     wait_for_engine_startup(
[1;36m(APIServer pid=298084)[0;0m     ~~~~~~~~~~~~~~~~~~~~~~~^
[1;36m(APIServer pid=298084)[0;0m         handshake_socket,
[1;36m(APIServer pid=298084)[0;0m         ^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m     ...<5 lines>...
[1;36m(APIServer pid=298084)[0;0m         coordinator.proc if coordinator else None,
[1;36m(APIServer pid=298084)[0;0m         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=298084)[0;0m     )
[1;36m(APIServer pid=298084)[0;0m     ^
[1;36m(APIServer pid=298084)[0;0m   File "/NAS/caizj/miniconda3/envs/df/lib/python3.13/site-packages/vllm/v1/engine/utils.py", line 785, in wait_for_engine_startup
[1;36m(APIServer pid=298084)[0;0m     raise RuntimeError("Engine core initialization failed. "
[1;36m(APIServer pid=298084)[0;0m                        "See root cause above. "
[1;36m(APIServer pid=298084)[0;0m                        f"Failed core proc(s): {finished}")
[1;36m(APIServer pid=298084)[0;0m RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
